---
commitizen:
  annotated_tag: true
  name: cz_conventional_commits
  tag_format: $version
  update_changelog_on_bump: true
  version: 0.5.0
  version_scheme: semver
  version_files: 
    exercises/part1/exercise1.6-1.11/unicafe/package.json:version
